### ISSUE TITLE
File类无法正确被使用

### ISSUE THREAD

**Issue by harry-xi** [LiteLDev/HelperLib#16]
#15 
移除了关键字，目前补全库在通过`tsconfing.json`文件(或编译时)指定使tsc不自动包含`lib.dom.d.ts`时表现是正常的，但是不做配置直接使用会发生编辑器无法正确找到补全库定义的File问题

考虑到llse-js的实际环境与浏览器相差甚大，在使用typescript时使用`--noLib`选项并不会造成明显的麻烦，因此这一现存问题对于ts影响有限

对于js，这确实有个麻烦

**Comment by lgc2333** [comment]
https://github.com/LiteLDev/LiteLoaderBDS/blob/main/ScriptEngine/assets/BaseLib.js#L401
编程时使用`file`即可
